### ISSUE TITLE
Canvas rendering ?

### ISSUE THREAD

**Issue by vogloblinsky** [lottielab/lottie-player#5]
Hi,

Is it possible to use canvas rendering ?

I need to do a dynamic animated gif in the browser of the Lottie animation. With a lottiefiles.com animation it works fine, but not yours.

Thanks

**Comment by geomaster** [comment]
Hi @vogloblinsky! This player does not support the canvas renderer.

Can you expand a bit more on your use-case? Do you mean rendering a Lottie to a gif animation in a browser environment? This should be doable without relying on the canvas renderer. If you share a bit more detail, I might be able to help guide you in the right direction.

**Comment by vogloblinsky** [comment]
I have a design with texts. Final usecase is to render an animated gif of the Lottie animation in the browser.
It works fine with the official player.
Your’s seems to be more complicated
And the final pain point is that text boxes from Figma are rendered directly in svg points and not in an svgtextelement, so I am not able to update dynamically them in the browser.
The final solution is to export the Figma frame to After Effects, do the animation, and export in Lottie, where it use in the Svgrenderer Svgtextelements
