### ISSUE TITLE
Autoplay attribute has no effect in web component

### ISSUE THREAD

**Issue by tobiaslockley** [lottielab/lottie-player#7]
Animations autoplay by default, but setting autoplay to either false or 0 has no effect.

Demo: https://jsfiddle.net/te843bkf/

**Comment by geomaster** [comment]
Thank you for the report @tobiaslockley, and I'm sorry for this omission. A fix was just released as part of [v1.1.2](https://github.com/lottielab/lottie-player/releases/tag/v1.1.2) 🎉
